### PR TITLE
Legacy Packet Adapter

### PR DESCRIPTION
**Pull request by Nixuge**
Very rough edges but had free time so why not

Confirmed to work on 1.7.10 -> 1.12.2 instead of just 1.8.8

TODOs:
- [x] Change the name of RandomUtils
- [ ] Actually test other versions (urgent), especially 1.7 & 1.12.2 as those are pretty much the main point of this PR
- [x] Cache more reflections things (See RandomUtils#22)
- [x] Test one thing that I couldn't manage to trigger (See TeamsPacketAdapterImpl.java#97, first part also in the tests for 1.8.8 only and passing)
- [x] Remove the debug print for last point
- [x] (idk?) add a dash in the middle of the packet adapter name (legacy-reflections instead of legacyreflections? Named it like that bc you can't have a - in java classes)
& probably some other things I forgot
- [x] add collision rule

Maybe TODO:
- [x] Yoink out 1.8.8 packet adapter? This packet adapter is basically the exact same one as the 1.8.8 one but w reflections in it. (Would break people's build.gradle, altho easily fixable)

### CODE REVIEW

**Comment by vytskalt** [comment]
I think we remove the 1.8 adapter and rename this one to just `legacy` since I don't see a reason for 1.8 to exist anymore (performance diff should be minimal and it doesn't matter anyway since it's all done async). For backwards compat the `v1_8_R3` module could stay and would just do something like `implementation(project(":legacy"))` in the build.gradle.

**Comment by Nixuge** [comment]
From a quick glance, most likely place that's failing in 1.7 with nothing changed is in sendScore:
```java
  @Override
  public void sendScore(
...
  ) {
    Object packet = packetPlayOutScoreboardScoreConstructor.invoke(entry);
    PacketAccessors.SCORE_OBJECTIVE_NAME_FIELD.set(packet, objectiveName);
    PacketAccessors.SCORE_VALUE_FIELD.set(packet, value);
//    Removed - not in 1.7
//    PacketAccessors.SCORE_ACTION_FIELD.set(packet, enumScoreboardActionChange);
    sender.sendPacket(players, packet);
  }
```

In FastBoard, they still do something for the action field even in 1.7:
```java
        if (VersionType.V1_8.isHigherOrEqual()) {
            Object enumAction = action == ScoreboardAction.REMOVE
                    ? ENUM_SB_ACTION_REMOVE : ENUM_SB_ACTION_CHANGE;
            setField(packet, ENUM_SB_ACTION, enumAction);
        } else {
            setField(packet, int.class, action.ordinal(), 1); // Action
        }
```

**Comment by Nixuge** [comment]
image
And indeed that was the fix

Added this in PacketAccessors:
```java
  public static final FieldAccessor<Object, Integer> SCORE_ACTION_FIELD_1_7 =
    ReflectUtil.findField(packetPlayOutScoreboardScoreClass, 1, int.class);
```

Then in ObjectivePacketAdapterImpl replaced:
```java
PacketAccessors.SCORE_ACTION_FIELD.set(packet, enumScoreboardActionChange);
```
with
```java
PacketAccessors.SCORE_ACTION_FIELD_1_7.set(packet, 0); // 0 = CHANGE, int value yoinked from FastBoard
```

**Comment by Nixuge** [comment]
Unfortunately, as excepted, 1.6 doesn't work either with that last change.

**Comment by Nixuge** [comment]
Not sure why the test is failing btw, iirc it worked correctly when I tried it

**Pull request merged**
